// console.log("hello js");
// const a=12;
// if(a>10){
//     let b=23;
//     a=40;
//     console.log("a="+a);
// }
// console.log("hi, a="+b);

// function fun(a,b,c){
//     console.log("heee");
//     return a+b+c;
// }
// let data=fun(12,5,10);
// console.log(data);

// function selectlanguage(language="no compiler selected"){
//     let data;
//     if (language=="c")
//     {
//          function cCompiler(){
//         return "C Compiler";
//     }
//     data=cCompiler();
//     }
//     if (language=="java"){
//         function javaCompiler(){
//         return "Java Compiler";

// }
// data=javaCompiler;

// }
// return data;
// }
// const result=selectlanguage("c");
// console.log(result);



// const div=document.getElementByIdClassName("parent");
// console.dir(div);
// div[0].innerHTML="<h2>ABES ENGINEERING COLLEGE</h2>";
// const h1=document.createElement("h1");
// h1.innerText="this is generated by dom";
// h1.style.backgroundColor='cyan';
// console.log(h1);
// div[0].appendChild(h1);
// const ima=document.createElement('img');
// img.src="C:\Users\Arun Kumar\OneDrive\Documents\Desktop\FSDAIML\FSDAIMLB\JSwork\download.jpeg";
// img.setAttribute("height","200");
// console.log(img);
// div[0].appendChild(img);

const disp=document.getElementById("disp";
    console.dir(disp);
    function getData(){
        console.log("getdata Called");
        disp.innerHTML=
    }
)



